### ISSUE TITLE
jupyter lab  

### ISSUE THREAD

**Issue by jmbertoncelli** [pixiedust/pixiedust#679] opened 2018-05-21 11:54 UTC
Hello,

I did install pixiedust  but because of JavaScript output is disabled in JupyterLab I cannot leverage
display and progress bar...

any idea or does pixiedust not ready yet for jupyter lab?

thanks

JM

**Comment by DTAIEB** [comment] 2018-05-22 13:06
@jmbertoncelli PixieDust does not yet support Jupyter Lab, It's on the backlog but we don't have an ETA yet.

**Comment by fperez** [comment] 2018-08-08 15:28
It seems this is a duplicate of #613, perhaps better to close here and focus discussion over there?

**Comment by DTAIEB** [comment] 2018-08-10 02:40
Agreed, closing this ticket

**Closed by DTAIEB** 2018-08-10 02:40 UTC
